GET http://localhost:3001/api/blogs

###

DELETE http://localhost:3001/api/blogs/id:

###

PUT http://localhost:3001/api/blogs/id:

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
      "username": "surani",
      "name": "surani",
      "password": "surani"
}





